/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#a8cfbc",
        "on-secondary-fixed": "#002117",
        "surface-tint": "#4edea3",
        "on-primary": "#003824",
        "on-tertiary-fixed": "#002115",
        "tertiary-fixed": "#c3ecd7",
        "primary-container": "#10b981",
        "on-secondary-container": "#83c2a9",
        "secondary-container": "#0b513d",
        "secondary-fixed": "#b0f0d6",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#84ab98",
        "secondary-fixed-dim": "#95d3ba",
        "tertiary": "#a8cfbc",
        "inverse-surface": "#dde4df",
        "error-container": "#93000a",
        "outline": "#86948a",
        "inverse-primary": "#006c49",
        "primary-fixed": "#6ffbbe",
        "on-surface": "#dde4df",
        "surface-bright": "#333b37",
        "primary": "#4edea3",
        "on-tertiary-fixed-variant": "#294e3f",
        "inverse-on-surface": "#2b322e",
        "error": "#ffb4ab",
        "background": "#0e1512",
        "on-background": "#dde4df",
        "on-primary-container": "#00422b",
        "on-primary-fixed": "#002113",
        "surface-container-low": "#161d1a",
        "surface-variant": "#2f3633",
        "surface-container-lowest": "#09100d",
        "on-error": "#690005",
        "on-secondary": "#003829",
        "on-surface-variant": "#bbcabf",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#1b3f31",
        "outline-variant": "#3c4a42",
        "surface-container": "#1a211e",
        "secondary": "#95d3ba",
        "surface-container-highest": "#2f3633",
        "on-tertiary": "#113729",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#0b513d",
        "surface-container-high": "#242c28",
        "surface-dim": "#0e1512",
        "surface": "#0e1512",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        sm: "12px",
        lg: "48px",
        md: "24px",
        gutter: "24px",
        "margin-desktop": "64px",
        base: "8px",
        xl: "80px",
        xs: "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        headline: ["Hanken Grotesk", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
