version: '3.8'

services:
  backend:
    entrypoint: ["./entrypoint.dev.sh"]
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Biarkan data prisma local ter-sync
      - /app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    # Pada mode dev, kita jalankan "npx prisma generate && npm run dev"
    command: sh -c "npx prisma generate && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_MQTT_WS_URL=ws://localhost:9001
      - DATABASE_URL=postgresql://earn_user:earn_password@db:5432/earn_db?schema=public
      # WATCHPACK_POLLING=true memastikan hot-reloading Next.js bekerja di Windows dengan Docker volume mounts
      - WATCHPACK_POLLING=true
